import type { NextPage } from "next";
import Head from "next/head";
import { QueryClientProvider, QueryClient } from "react-query";
import CollectionList from "../components/collection-list";

const queryClient = new QueryClient();

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home | Acidgreen</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main className="container mx-auto">
        <QueryClientProvider client={queryClient}>
          <CollectionList />
        </QueryClientProvider>
      </main>
    </>
  );
};

export default Home;
