import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import { Product } from "../../components/product";

const Products: NextPage = () => {

  const router = useRouter();
  const productHandle = router.query.product;

  if (!productHandle) return <>Loading Product...</>;
  return (
    <>
      <Head>
        <title>{productHandle}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white">
        <Product handle={productHandle} />
      </main>
    </>
  );
};

export default Products;